version: '3.8'

services:

  app-service:
    build:
        context: "app"
        dockerfile: Dockerfile
    container_name: app-service
    ports:
      - "5000:5000"

  blueprints-service:
    build:
        context: "blueprints"
        dockerfile: Dockerfile
    container_name: blueprints-service
